/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "LBN_Thrift_constants.h"

namespace LBN_Thrift {

const LBN_ThriftConstants g_LBN_Thrift_constants;

LBN_ThriftConstants::LBN_ThriftConstants() {
}

} // namespace

