/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef LBN_Thrift_CONSTANTS_H
#define LBN_Thrift_CONSTANTS_H

#include "LBN_Thrift_types.h"

namespace LBN_Thrift {

class LBN_ThriftConstants {
 public:
  LBN_ThriftConstants();

};

extern const LBN_ThriftConstants g_LBN_Thrift_constants;

} // namespace

#endif
